steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/laeploo-python',
        '.',
      ]
  # push the container images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/laeploo-python']
  # deploy the container images to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'laeploo-python',
        '--image',
        'gcr.io/$PROJECT_ID/laeploo-python',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--quiet',
      ]
  # route 100% of traffic to the newly deployed revision
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'services',
        'update-traffic',
        'laeploo-python',
        '--to-latest',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--quiet',
      ]
timeout: 2400s